# Generated by Django 3.2.18 on 2023-03-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Newspaper',
        ),
    ]
